services:

  postgres:
    image: postgres:17
    container_name: tp5-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tp5_tareas
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build:
      context: ./backend
    container_name: tp5-backend
    ports:
      - "3000:3000"
    environment:
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: tp5_tareas
      DB_HOST: postgres
      DB_PORT: 5432
    depends_on:
      - postgres

  frontend:
    build:
      context: .
    container_name: tp5-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  postgres_data: